<?php
/**
 * @category    MineWhat
 * @package     MineWhat_Insights
 * @copyright   Copyright (c) MineWhat
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_product = $this->getCurrentProduct() ?>
<?php 
	$_associated_products = $this->getAssociatedProducts($_product);
	$associated_ids = Array();
?>
<script type="text/mwdata">
//<![CDATA[	
	var _mwdata = _mwdata || {};
	
	_mwdata['product'] = {};
	_mwdata['product'].id = '<?php echo $_product->getId() ?>';
	_mwdata['product'].sku = '<?php echo $_product->getSku() ?>';
	_mwdata['product'].cat = '<?php echo json_encode($_product->getCategoryIds()) ?>';
	_mwdata['product'].price = '<?php echo $_product->getPrice() ?>';	
	
	<?php if($_associated_products != null): ?>
		_mwdata['associated_products'] = [];
	<?php endif; ?>

	<?php foreach($_associated_products as $simple_product): 
        	$product_info = Array();
		$associated_ids[] = $simple_product->getId();
		$product_info['id'] = $simple_product->getId();
		$product_info['sku'] = $simple_product->getSku();
		$product_info['price'] = $simple_product->getPrice();
	?>
		_mwdata['associated_products'].push(<?php echo json_encode($product_info) ?>);
	<?php endforeach; ?>
//]]>	
</script>

<script type="text/javascript">
//<![CDATA[
	var _mwapi = _mwapi || [];
	_mwapi.push(['trackEvent', 'product', '<?php echo $_product->getId() ?>', '<?php echo json_encode($associated_ids) ?>']);
//]]>
</script>
