<?php
/**
 * @category    MineWhat
 * @package     MineWhat_Insights
 * @copyright   Copyright (c) MineWhat
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_product = $this->getProductToShoppingCart() ?>
<?php if ($_product && $_product["id"]) { ?>
<script type="text/javascript">
//<![CDATA[
	var _mwapi = _mwapi || [];
    	_mwapi.push(['trackEvent', 'cart', '<?php echo $_product["id"] ?>', '<?php echo $_product["sku"] ?>', '<?php echo json_encode($_product["parentId"]) ?>', '<?php echo json_encode($_product["bundle"]) ?>']);
//]]>
</script>
<?php } ?>
