<?php
/**
 * @category    MineWhat
 * @package     MineWhat_Insights
 * @copyright   Copyright (c) MineWhat
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_product = $this->getProductToShoppingCart() ?>
<?php if ($_product && $_product->getId()): ?>
<script type="text/javascript">
	var _mwapi = _mwapi || [];
    	_mwapi.push(['trackEvent', 'cart', '<?php echo $_product->getId() ?>']);
</script>
<?php endif; ?>
