<?php
/**
 * @category    MineWhat
 * @package     MineWhat_Insights
 * @copyright   Copyright (c) MineWhat
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if (($orderInfo = $this->getOrderInfo())) { ?>
<script type="text/javascript">
//<![CDATA[
	var _mwapi = _mwapi || [];
	var data [];
	<?php foreach ($orderInfo['items'] as $product) { ?>
		data.push({_id: '<?php echo $product["id"] ?>', qty: '<?php echo intval($product["qty"]) ?>', sku: '<?php echo $product["sku"] ?>', price: '<?php echo $product["price"] ?>', parentId: '<?php echo $product["parentId"] ?>', bundle: '<?php echo json_encode($product["bundle"]) ?>'});
	<?php } ?>
  	_mwapi.push(['trackEvent', 'buy', 'mwdirect', data]);
//]]>
</script>
<?php } ?>
