<?php
/**
 * @category    MineWhat
 * @package     MineWhat_Insights
 * @copyright   Copyright (c) MineWhat
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if (($orderInfo = $this->getOrderInfo())): ?>
<script type="text/javascript">
	var _mwapi = _mwapi || [];
	<?php foreach ($orderInfo->getItems() as $product): ?>
		_mwapi.push(['trackEvent', 'buy', '<?php echo $product->getId() ?>', '<?php echo intval($product->getQty()) ?>']);
	<?php endforeach; ?>
</script>
<?php endif; ?>
